# Generated by Django 5.0.1 on 2024-05-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=75)),
                ('manufacturer', models.CharField(blank=True, max_length=75, null=True)),
                ('model', models.CharField(blank=True, max_length=75, null=True)),
                ('number_of_processors', models.CharField(blank=True, max_length=75, null=True)),
                ('system_type', models.CharField(blank=True, max_length=75, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=75, null=True)),
                ('processor_name', models.CharField(blank=True, max_length=75, null=True)),
                ('number_of_cores', models.CharField(blank=True, max_length=75, null=True)),
                ('max_clock_speed_ghz', models.CharField(blank=True, max_length=75, null=True)),
                ('graphics_card', models.CharField(blank=True, max_length=75, null=True)),
                ('bios_version', models.CharField(blank=True, max_length=75, null=True)),
                ('product', models.CharField(blank=True, max_length=75, null=True)),
                ('base_board_serial_number', models.CharField(blank=True, max_length=75, null=True)),
                ('number_of_memory_slots', models.CharField(blank=True, max_length=75, null=True)),
                ('total_ram_gb', models.CharField(blank=True, max_length=75, null=True)),
                ('used_ram_slots', models.CharField(blank=True, max_length=75, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=75, null=True)),
                ('disk_drive_model', models.CharField(blank=True, max_length=75, null=True)),
                ('disk_size_gb', models.CharField(blank=True, max_length=75, null=True)),
                ('media_type', models.CharField(blank=True, max_length=75, null=True)),
                ('disk_partition_name', models.CharField(blank=True, max_length=75, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=75, null=True)),
                ('os_version', models.CharField(blank=True, max_length=75, null=True)),
                ('os_build_number', models.CharField(blank=True, max_length=75, null=True)),
                ('office_version', models.CharField(blank=True, max_length=75, null=True)),
                ('office_license_status', models.CharField(blank=True, max_length=75, null=True)),
                ('disk_usage_percentage', models.CharField(blank=True, max_length=75, null=True)),
                ('ram_brands', models.CharField(blank=True, max_length=75, null=True)),
                ('average_ram_speed', models.CharField(blank=True, max_length=75, null=True)),
                ('ram_slot_types', models.CharField(blank=True, max_length=75, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tunbisapp.unit')),
            ],
        ),
    ]
