# Generated by Django 5.0.1 on 2024-05-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0002_computerinformations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputerInformations',
            new_name='Computer_Informations',
        ),
    ]
