# Generated by Django 5.0.1 on 2024-05-03 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0003_rename_computerinformations_computer_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_informations',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='computer_informations',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computer_informations',
            name='network_used',
            field=models.CharField(blank=True, choices=[('Internet', 'Internet'), ('PolNet', 'PolNet'), ('KGYS', 'KGYS')], max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='computer_informations',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
