# Generated by Django 5.0.1 on 2024-05-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0004_computer_informations_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_installed', models.BooleanField(default=False, verbose_name='Parça Takıldı')),
                ('os_installed', models.BooleanField(default=False, verbose_name='İşletim Sistemi Kuruldu')),
                ('other', models.BooleanField(default=False, verbose_name='Diğer İşlemler')),
                ('requester_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tunbisapp.computer_informations')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Computer Actions',
            },
        ),
    ]
