# Generated by Django 5.0.1 on 2024-05-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0005_computeraction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputerAction',
            new_name='computer_action',
        ),
    ]
