# Generated by Django 5.0.1 on 2024-05-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0006_rename_computeraction_computer_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer_action',
            old_name='notes',
            new_name='action_notes',
        ),
        migrations.AddField(
            model_name='computer_action',
            name='requester_notes',
            field=models.TextField(blank=True),
        ),
    ]
