# Generated by Django 5.0.1 on 2024-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0007_rename_notes_computer_action_action_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_action',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
