# Generated by Django 5.1.1 on 2024-10-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0009_tebsgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tebsgroup',
            table='tebs_group',
        ),
    ]
