# Generated by Django 5.1.1 on 2024-11-01 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0010_alter_tebsgroup_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tebsuser',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tebsuser',
            name='password_last_changed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tebsuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tebsuser',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
