# Generated by Django 5.1.1 on 2024-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0011_tebsuser_force_password_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tebsuser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('food', 'En Sevdiğiniz Yemek'), ('book', 'En Sevdiğiniz Kitap'), ('teacher', 'İlkokul Öğretmeninizin Adı'), ('car', 'İlk Arabanızın Markası'), ('movie', 'En Sevdiğiniz Film'), ('friend', 'En Yakın Arkadaşınızın Adı')], max_length=50, null=True),
        ),
    ]
