# Generated by Django 5.1.1 on 2024-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0012_alter_tebsuser_security_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tebsuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
