# Generated by Django 5.1.1 on 2024-11-07 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0013_alter_tebsuser_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterScannerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Printer', 'Yazıcı'), ('Scanner', 'Tarayıcı')], default='Printer', max_length=20)),
                ('device_name', models.CharField(max_length=75)),
                ('manufacturer', models.CharField(blank=True, max_length=75, null=True)),
                ('model', models.CharField(blank=True, max_length=75, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=75, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('network_used', models.CharField(blank=True, choices=[('Internet', 'Internet'), ('PolNet', 'PolNet'), ('KGYS', 'KGYS')], max_length=75, null=True)),
                ('color_mode', models.CharField(choices=[('Color', 'Renkli'), ('Monochrome', 'Siyah Beyaz')], default='Monochrome', max_length=20)),
                ('print_speed_ppm', models.IntegerField(blank=True, help_text='Dakikada basılan sayfa sayısı (PPM)', null=True)),
                ('scan_speed_ipm', models.IntegerField(blank=True, help_text='Dakikada taranan görüntü sayısı (IPM)', null=True)),
                ('max_resolution_dpi', models.IntegerField(blank=True, help_text='Maksimum çözünürlük (DPI)', null=True)),
                ('duplex', models.BooleanField(default=False, help_text='Çift taraflı baskı/tarama desteği var mı?')),
                ('wireless_capability', models.BooleanField(default=False, help_text='Kablosuz bağlantı desteği var mı?')),
                ('paper_capacity', models.IntegerField(blank=True, help_text='Kağıt kapasitesi (sayfa)', null=True)),
                ('toner_level', models.CharField(blank=True, help_text='Toner doluluk oranı (%)', max_length=10, null=True)),
                ('drum_unit_life_remaining', models.CharField(blank=True, help_text='Drum ünitesinin kalan ömrü (%)', max_length=10, null=True)),
                ('scan_unit_life_remaining', models.CharField(blank=True, help_text='Tarayıcı ünitesinin kalan ömrü (%)', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tunbisapp.unit')),
            ],
        ),
    ]
