# Generated by Django 5.1.1 on 2024-11-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0014_printerscannerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='printerscannerinformation',
            name='connection_interface',
            field=models.CharField(choices=[('LAN', 'LAN'), ('USB', 'USB')], default='LAN', help_text='Bağlantı Arayüzü', max_length=10),
        ),
    ]
