# Generated by Django 5.1.4 on 2024-12-19 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0016_alter_printerscannerinformation_color_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tebsuser',
            name='birthday',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
