# Generated by Django 5.1.4 on 2024-12-27 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0018_alter_printerscannerinformation_device_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(choices=[('paper_jam', 'Kağıt Sıkışması'), ('ink_toner', 'Toner veya Kartuş Sorunu'), ('hardware', 'Donanım Arızası'), ('software', 'Yazılım Sorunu'), ('network', 'Ağ Bağlantı Sorunu'), ('other', 'Diğer')], default='other', max_length=20, verbose_name='Arıza Türü')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Arıza Durumu')),
                ('toner_replaced', models.BooleanField(default=False, verbose_name='Toner Değiştirildi')),
                ('firmware_updated', models.BooleanField(default=False, verbose_name='Firmware Güncellendi')),
                ('other', models.BooleanField(default=False, verbose_name='Diğer İşlemler')),
                ('requester_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('action_notes', models.TextField(blank=True, verbose_name='İşlem Notları')),
                ('requester_notes', models.TextField(blank=True, verbose_name='Talep Notları')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_printer_actions', to=settings.AUTH_USER_MODEL, verbose_name='İşlem Yapan')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tunbisapp.printerscannerinformation', verbose_name='Yazıcı')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_printer_actions', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name_plural': 'Printer Actions',
            },
        ),
    ]
