# Generated by Django 5.1.4 on 2024-12-29 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0019_printeraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('computer', 'Bilgisayar'), ('printer', 'Yazıcı/Tarayıcı'), ('tablet', 'Tablet')], max_length=20)),
                ('part_installed', models.BooleanField(default=False, verbose_name='Parça Takıldı')),
                ('os_installed', models.BooleanField(default=False, verbose_name='İşletim Sistemi Kuruldu')),
                ('ink_replaced', models.BooleanField(default=False, verbose_name='Kartuş Değiştirildi')),
                ('paper_jam_fixed', models.BooleanField(default=False, verbose_name='Kağıt Sıkışması Giderildi')),
                ('other', models.BooleanField(default=False, verbose_name='Diğer İşlemler')),
                ('action_notes', models.TextField(blank=True, verbose_name='İşlem Notları')),
                ('requester_notes', models.TextField(blank=True, verbose_name='Talep Eden Notları')),
                ('requester_date', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_actions', to='tunbisapp.computer_informations')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_fault_actions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fault_actions', to='tunbisapp.printerscannerinformation')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fault_actions', to=settings.AUTH_USER_MODEL, verbose_name='Talep Eden')),
            ],
            options={
                'verbose_name_plural': 'Fault Actions',
            },
        ),
    ]
