# Generated by Django 5.1.4 on 2025-01-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0021_alter_faultaction_action_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faultaction',
            name='hardware_fixed',
            field=models.BooleanField(default=False, null=True, verbose_name='Donanım Sorunu Giderildi'),
        ),
        migrations.AddField(
            model_name='faultaction',
            name='software_fixed',
            field=models.BooleanField(default=False, null=True, verbose_name='Yazılım Sorunu Giderildi'),
        ),
        migrations.AlterField(
            model_name='printerscannerinformation',
            name='device_type',
            field=models.CharField(choices=[('Printer', 'Printer'), ('Scanner', 'Scanner'), ('Printer-Scanner', 'Printer-Scanner'), ('All-In-One Printers', 'All-In-One Printers')], default='Printer', max_length=75),
        ),
    ]
