# Generated by Django 5.1.4 on 2025-02-24 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0023_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='DeviceRequest',
        ),
    ]
