# Generated by Django 5.1.4 on 2025-02-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0024_rename_request_devicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerequest',
            name='device_type',
            field=models.CharField(choices=[('printer', 'Siyah-Beyaz Yazıcı'), ('color_printer', 'Renkli Yazıcı'), ('scanner', 'Tarayıcı'), ('computer', 'Bilgisayar'), ('tablet', 'Tablet Bilgisayar')], max_length=20),
        ),
    ]
