# Generated by Django 5.1.4 on 2025-02-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0025_alter_devicerequest_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='devicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('delivered', 'Teslim Edildi')], default='Beklemede', max_length=20),
        ),
    ]
