# Generated by Django 5.1.4 on 2025-03-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunbisapp', '0027_alter_devicerequest_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('computer', 'Bilgisayar'), ('printer', 'Yazıcı'), ('color_printer', 'Renkli Yazıcı'), ('scanner', 'Tarayıcı'), ('color_printer_scanner', 'Çok Fonksiyonlu Renkli Yazıcı / Tarayıcı'), ('Çok Fonksiyonlu Yazıcı / Tarayıcı', 'Printer Scanner'), ('tablet', 'Tablet Bilgisayar')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('received_date', models.DateTimeField(auto_now_add=True)),
                ('is_allocated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('computer', 'Bilgisayar'), ('printer', 'Yazıcı'), ('color_printer', 'Renkli Yazıcı'), ('scanner', 'Tarayıcı'), ('color_printer_scanner', 'Çok Fonksiyonlu Renkli Yazıcı / Tarayıcı'), ('Çok Fonksiyonlu Yazıcı / Tarayıcı', 'Printer Scanner'), ('tablet', 'Tablet Bilgisayar')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('allocated_date', models.DateTimeField(auto_now_add=True)),
                ('allocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunbisapp.unit')),
            ],
        ),
    ]
