version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: msc_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - msc_postgres_data:/var/lib/postgresql/data
    networks:
      - msc-net

volumes:
  msc_postgres_data:

networks:
  msc-net:
    external: true