# Generated by Django 5.1.4 on 2024-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eeuser',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
