# Generated by Django 5.1.4 on 2025-02-06 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanagement', '0002_eeuser_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_successful',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Nakit'), ('card', 'Kredi/Banka Kartı'), ('other', 'Diğer')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='easymanagement.order'),
        ),
    ]
