# Generated by Django 5.1.4 on 2025-02-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymanagement', '0003_rename_created_at_payment_payment_date_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='payment',
            name='is_successful',
            field=models.BooleanField(default=False),
        ),
    ]
