"""
Django settings for EasyEating project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from django.contrib import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_xx0r3&!5j3h#g@5_6n^s#k4%s7bbv-a$3eu1@fm-*9*!93#dn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["162.162.5.11","127.0.0.1","localhost","192.168.137.1"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
     'daphne',
    'django.contrib.staticfiles',
    'channels',
    'pages',
    'easymanagement',
    'account',
    'order',
    'payment',
    'debug_toolbar',
   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'logging_helper.middleware.UserActivityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
  
]

ROOT_URLCONF = 'EasyEating.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EasyEating.wsgi.application'

ASGI_APPLICATION = 'EasyEating.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'EasyEating',
		'USER': 'admin',
		'PASSWORD': 'Ms.1806730971',
		'HOST':'database-1.cj868o8228rt.eu-north-1.rds.amazonaws.com',
		'PORT':'3306',
	}
}

#DATABASES = {
#	'default': {
#		'ENGINE': 'django.db.backends.mysql',
#		'NAME': 'dbEasyEating',
#		'USER': 'root',
#		'PASSWORD': 'Ms1806730971',
#		'HOST':'localhost',
#		'PORT':'3306',
#	}
#}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_ROOT= BASE_DIR / "img"
MEDIA_URL="/media/"
LOGIN_URL="/account/login"

#Custom User Model
AUTH_USER_MODEL = 'easymanagement.EEUser'
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',  # Eski şifreleme uyumluluğu için
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',  # Güvenli algoritmalar
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

MESSAGE_TAGS = {
    messages.DEBUG:"alert-secondary",
    messages.SUCCESS:"alert-success",
    messages.INFO:"alert-info",
    messages.WARNING:"alert-warning",
    messages.ERROR:"alert-danger",

    
}

# settings.py
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_errors.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
