version: '3.8'

services:
  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk_network

  # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    environment:
      - "LOGSTASH_HTTP_HOST=0.0.0.0"
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk_network
    depends_on:
      - elasticsearch

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=Ms1806730971
      - ELASTICSEARCH_SERVICE_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlLXRva2VuOk5uNFhPNVFrUUEtTlhZQldTTEh3blE
    ports:
      - "5601:5601"
    networks:
      - elk_network
    depends_on:
      - elasticsearch
  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.2
    container_name: filebeat
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_user
      - ELASTICSEARCH_PASSWORD=Ms1806730971
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml  # Filebeat konfigürasyon dosyasını mount ediyoruz
      - /var/log:/var/log  # Log dosyalarını mount ediyoruz
    networks:
      - elk_network
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:

networks:
  elk_network:
    driver: bridge
