version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--auth"] # Yetkilendirme etkinleştirildi

volumes:
  mongodb_data:
    driver: local

