# Generated by Django 5.1.4 on 2025-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tebs_bulut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('.docx', 'Word'), ('.xlsx', 'Excel'), ('.pdf', 'Pdf')], max_length=20),
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
