version: '3.8'

services:
  odoo:
    image: odoo:18
    container_name: odoo
    ports:
      - "8069:8069"  # Odoo arayüzüne 8069 portu üzerinden erişim
    volumes:
      - odoo_data:/var/lib/odoo  # Odoo verileri kalıcı olacak şekilde volume bağlıyoruz
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo_password
    depends_on:
      - odoo-db

  odoo-db:
    image: postgres:13
    container_name: odoo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password
      POSTGRES_DB: odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Veritabanı verilerini kalıcı tutmak için volume

volumes:
  odoo_data:
  postgres_data:
